openapi: 3.0.0
info:
  title: Guidable API
  description: API Provided by guidable.in.
  version: '20220601'
servers:
  - url: http://localhost/8081
paths:
  /roadmaps:
    get:
      summary: Get List of Roadmaps
      operationId: getRoadMaps
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateRoadmapResponse'
    post:
      summary: Create a Roadmap
      operationId: createRoadmap
      requestBody:
        description: Roadmap details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoadmapDetail'
        required: true
      responses:
        200:
          description: Roadmap Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoadmapResponse'
      x-codegen-request-body-name: roadmaps
  /roadmaps/{roadmapId}:
    get:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Get List of Roadmaps
      operationId: getRoadMap
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoadmapResponse'

components:
  schemas:
    CreateRoadmapDetail:
      type: object
      properties:
        id:
          type: string
          example: '12345'
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        parentId:
          type: string
          example: "id-of-roadmap-collection"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        originalAuthor:
          type: string
        updatedBy:
          type: string
        isSharable:
          type: boolean


    CreateRoadmapResponse:
      type: object
      properties:
        id:
          type: string
          example: '12345'
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        parentId:
          type: string
          example: "id-of-roadmap-collection"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        originalAuthor:
          type: string
        updatedBy:
          type: string
        publicMetadata:
          type: object
          properties:
            isSharable:
              type: boolean
            publicLinkKey:
              type: string
            views:
              type: integer
              format: int64
              example: 100
            likes:
              type: integer
              format: int64
              example: 42

    Checkpoints:
      type: object
      properties:
        checkpointKey:
          type: string
        name:
          type: string
        shortDescription:
          type: string
        detailedDescription:
          type: string
        quickLink:
          type: string
        isComplete:
          type: boolean



