openapi: 3.0.0
info:
  title: Guidable API
  description: API Provided by guidable.in.
  version: '20220601'
servers:
  - url: http://localhost/8081
paths:
  /roadmaps:
    get:
      security:
        - bearerAuth: [ ]
      parameters:
        - in : header
          name: Authorization
          schema:
            type: string
      summary: Get List of Roadmaps
      operationId: getRoadMaps
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateRoadmapResponse'
    post:
      summary: Create a Roadmap
      operationId: createRoadmap
      security:
        - bearerAuth: [ ]
      parameters:
        - in: header
          name : Authorization
          schema:
            type: string
      requestBody:
        description: Roadmap details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoadmapDetail'
        required: true
      responses:
        200:
          description: Roadmap Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoadmapResponse'
      x-codegen-request-body-name: roadmaps
  /roadmaps/{roadmapId}:
    get:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Get List of Roadmaps
      operationId: getRoadMap
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoadmapResponse'
    put:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Update a Roadmap
      operationId: updateRoadmap
      requestBody:
        description: Roadmap details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoadmapDetail'
        required: true
      responses:
        200:
          description: Roadmap updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoadmapResponse'
          x-codegen-request-body-name: roadmaps
  /roadmaps/{roadmapId}/actions/enableShareLink:
    post:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Create a sharable public link
      operationId: enableShareLink
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoadmapResponse'
  /roadmaps/{roadmapId}/actions/disableShareLink:
    post:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Mark resource as private
      operationId: disableShareLink
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoadmapResponse'


  /search/findByLinkKey/{linkKey}:
    get:
      parameters:
        - name: linkKey
          in: path
          required: true
          schema:
            type: string
      summary: Find a shared resource by linkKey
      operationId: findByLinkKey
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharableResourceResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateRoadmapDetail:
      type: object
      properties:
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        parentId:
          type: string
          example: "id-of-roadmap-collection"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        isSharable:
          type: boolean

    UpdateRoadmapDetail:
      type: object
      properties:
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        isSharable:
          type: boolean


    Checkpoints:
      type: object
      properties:
        checkpointKey:
          type: string
        name:
          type: string
        shortDescription:
          type: string
        detailedDescription:
          type: string
        quickLink:
          type: string
        isComplete:
          type: boolean

    SharableResourcePublicMetadata:
      type: object
      properties:
        isSharable:
          type: boolean
        publicLinkKey:
          type: string
        views:
          type: integer
          format: int64
          example: 100
        likes:
          type: integer
          format: int64
          example: 42

    CreateRoadmapResponse:
      type: object
      properties:
        id:
          type: string
          example: '12345'
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        parentId:
          type: string
          example: "id-of-roadmap-collection"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        originalAuthor:
          type: string
        updatedBy:
          type: string
        publicMetadata:
          $ref: "#/components/schemas/SharableResourcePublicMetadata"

    SharableResource:
      oneOf:
        - $ref: '#/components/schemas/CreateRoadmapResponse'

    SharableResourceResponse:
      type: object
      properties:
        objectType:
          type: string
          enum:
            - ROADMAP
            - ROADMAP_COLLECTION
        publicResource:
          $ref: '#/components/schemas/SharableResource'



