openapi: 3.0.0
info:
  title: Guidable API
  description: API Provided by guidable.in.
  version: '20220601'
servers:
  - url: http://localhost/8081
paths:
  /journey:
    post:
      summary: Create a Jouneys
      operationId: createJourney
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        description: Journey details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJourneyDetail'
        required: true
      responses:
        200:
          description: Journey Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JourneyResponse'
  /roadmaps:
    get:
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      summary: Get List of Roadmaps
      operationId: getRoadMaps
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoadmapResponse'
    post:
      summary: Create a Roadmap
      operationId: createRoadmap
      parameters:
        - $ref: "#/components/parameters/AuthorizationHeader"
      requestBody:
        description: Roadmap details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoadmapDetail'
        required: true
      responses:
        200:
          description: Roadmap Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadmapResponse'
      x-codegen-request-body-name: roadmaps
  /roadmaps/{roadmapId}:
    get:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Get List of Roadmaps
      operationId: getRoadMap
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadmapResponse'
    put:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Update a Roadmap
      operationId: updateRoadmap
      requestBody:
        description: Roadmap details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoadmapDetail'
        required: true
      responses:
        200:
          description: Roadmap updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadmapResponse'
          x-codegen-request-body-name: roadmaps
  /roadmaps/{roadmapId}/actions/enableShareLink:
    post:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Create a sharable public link
      operationId: enableShareLink
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadmapResponse'
  /roadmaps/{roadmapId}/actions/disableShareLink:
    post:
      parameters:
        - name: roadmapId
          in: path
          required: true
          schema:
            type: string
      summary: Mark resource as private
      operationId: disableShareLink
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadmapResponse'


  /search/findByLinkKey/{linkKey}:
    get:
      parameters:
        - name: linkKey
          in: path
          required: true
          schema:
            type: string
      summary: Find a shared resource by linkKey
      operationId: findByLinkKey
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharableResourceResponse'

components:
  schemas:
    CreateJourneyDetail:
      type: object
      properties:
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this journey to be a ML engineer"
        isSharable:
          type: boolean

    CreateRoadmapDetail:
      type: object
      properties:
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        parentId:
          type: string
          example: "id-of-roadmap-collection"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        isSharable:
          type: boolean

    UpdateRoadmapDetail:
      type: object
      properties:
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        isSharable:
          type: boolean


    Checkpoints:
      type: object
      properties:
        checkpointKey:
          type: string
        name:
          type: string
        shortDescription:
          type: string
        detailedDescription:
          type: string
        quickLink:
          type: string
        isComplete:
          type: boolean

    SharableResourcePublicMetadata:
      type: object
      properties:
        isSharable:
          type: boolean
        publicLinkKey:
          type: string
        views:
          type: integer
          format: int64
          example: 100
        likes:
          type: integer
          format: int64
          example: 42

    RoadmapResponse:
      type: object
      properties:
        id:
          type: string
          example: '12345'
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this roadmap to be a ML engineer"
        parentId:
          type: string
          example: "id-of-roadmap-collection"
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/Checkpoints"
        originalAuthor:
          type: string
        updatedBy:
          type: string
        publicMetadata:
          $ref: "#/components/schemas/SharableResourcePublicMetadata"

    JourneyResponse:
      type: object
      properties:
        id:
          type: string
          example: '12345'
        name:
          type: string
          example: "Journey to ML Engineer"
        description:
          type: string
          example: "Explore this journey to be a ML engineer"
        originalAuthor:
          type: string
        updatedBy:
          type: string
        publicMetadata:
          $ref: "#/components/schemas/SharableResourcePublicMetadata"

    SharableResource:
      oneOf:
        - $ref: '#/components/schemas/RoadmapResponse'
        - $ref: '#/components/schemas/JourneyResponse'

    SharableResourceResponse:
      type: object
      properties:
        objectType:
          type: string
          enum:
            - ROADMAP
            - ROADMAP_COLLECTION
        publicResource:
          $ref: '#/components/schemas/SharableResource'

  parameters:
    ## Headers
    AuthorizationHeader:
      name: Authorization
      in: header
      schema:
        type: string
      required: true






