openapi: 3.0.0
info:
  title: signup API
  description: API Provided by guidable.in.
  version: '20220601'
servers:
  - url: http://localhost:8081
paths:
  /validation/signup:
    post:
      summary: Create a Customer Signup
      operationId: customerSignUp
      requestBody:
        description: Signup details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDTO'
        required: true
      responses:
        201:
          description: Roadmap Created
        400:
          description: Username Already present

  /validation/authenticate:
    post:
      summary: Create a Customer Login
      operationId: customerLogin
      requestBody:
        description: Login details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        200:
          description: Login Success
          content:
            application/json:
              schema:
                type: string
  /validation/verifyRegistration:
    get:
      summary: Verify Registration Token
      operationId: verifyRegistration
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Verification Success
          content:
            application/json:
              schema:
                type: string
        401:
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
  /validation/reGenerateVerificationToken:
    post:
      summary: Resend VerificationToken
      operationId: reGenerateVerificationToken
      requestBody:
        description: Resend VerificationToken
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        200:
          description: Resend VerificationToken Success
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    SignUpDTO:
      type: object
      properties:
        customerUserName:
          type: string
        customerEmail:
          type: string
        customerPassword:
          type: string
        userRole:
           type: string
    AuthRequest:
      type: object
      properties:
        userName:
          type: string
        password:
          type: string
